--- # Notification and Handling events
- hosts: webgroup
  remote_user: ansible-server
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: install nginx appserver
    yum:
      name: nginx
      state: latest
    notify:
    - enable and start the nginx service
  handlers:
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted
